2023-03-11 11:29:19,686 INFO    MainThread:10921 [wandb_setup.py:_flush():68] Configure stats pid to 10921
2023-03-11 11:29:19,686 INFO    MainThread:10921 [wandb_setup.py:_flush():68] Loading settings from /home/sooraj/.config/wandb/settings
2023-03-11 11:29:19,686 INFO    MainThread:10921 [wandb_setup.py:_flush():68] Loading settings from /home/sooraj/sem/dl/assignment-1/wandb/settings
2023-03-11 11:29:19,686 INFO    MainThread:10921 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-11 11:29:19,686 INFO    MainThread:10921 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-11 11:29:19,687 INFO    MainThread:10921 [wandb_init.py:_log_setup():492] Logging user logs to /home/sooraj/sem/dl/assignment-1/wandb/run-20230311_112919-fcktt2s5/logs/debug.log
2023-03-11 11:29:19,687 INFO    MainThread:10921 [wandb_init.py:_log_setup():493] Logging internal logs to /home/sooraj/sem/dl/assignment-1/wandb/run-20230311_112919-fcktt2s5/logs/debug-internal.log
2023-03-11 11:29:19,687 INFO    MainThread:10921 [wandb_init.py:init():532] calling init triggers
2023-03-11 11:29:19,687 INFO    MainThread:10921 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-11 11:29:19,688 INFO    MainThread:10921 [wandb_init.py:init():554] re-initializing run, found existing run on stack: r2eyiwvn
2023-03-11 11:29:19,691 INFO    MainThread:10921 [wandb_run.py:_finish():1854] finishing run cs20b075/assignment-1/r2eyiwvn
2023-03-11 11:29:19,691 INFO    MainThread:10921 [jupyter.py:save_history():449] not saving jupyter history
2023-03-11 11:29:19,691 INFO    MainThread:10921 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-11 11:29:19,692 INFO    MainThread:10921 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-11 11:29:19,692 INFO    MainThread:10921 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-11 11:29:19,692 INFO    MainThread:10921 [wandb_run.py:_restore():2066] restore
2023-03-11 11:29:19,692 INFO    MainThread:10921 [wandb_run.py:_restore():2072] restore done
2023-03-11 11:30:02,908 INFO    MainThread:10921 [wandb_init.py:init():588] starting backend
2023-03-11 11:30:02,909 INFO    MainThread:10921 [wandb_init.py:init():592] setting up manager
2023-03-11 11:30:02,912 INFO    MainThread:10921 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-11 11:30:02,914 INFO    MainThread:10921 [wandb_init.py:init():599] backend started and connected
2023-03-11 11:30:02,936 INFO    MainThread:10921 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-11 11:30:02,936 INFO    MainThread:10921 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-11 11:30:02,937 INFO    MainThread:10921 [wandb_init.py:init():687] updated telemetry
2023-03-11 11:30:02,947 INFO    MainThread:10921 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
